from Animal import *

antelope = Antelope("Antelope", "black", 5, 20, False, 20)
bigfish = Bigfish("Big-fish", "black", 5, 20, False, 20)
littlefish = Littlefish("Little-fish", "black", 5, 20, False, 20)
bug = Bug("Bug", "black", 5, 20, False, 20)
chicken = Chicken("Chicken", "black", 5, 20, False, 20)
cow = Cow("Cow", "black", 5, 20, False, 20)
sheep = Sheep("Sheep", "black", 5, 20, False, 20)
bear = Bear("Bear", "black", 5, 20, False, 20)
fox = Fox("Fox", "black", 5, 20, False, 20)
giraffe = Giraffe("Giraffe", "black", 5, 20, False, 20)
lion = Lion("Lion", "black", 5, 20, False, 20)
panda = Panda("Panda", "black", 5, 20, False, 20)
grass = Grass()
leaves = Leaves()
print(antelope.eat(grass))
print(bigfish.eat(littlefish))
print(bug.eat(leaves))
print(bear.eat(bigfish))
print(bear.eat(bug))
print(bear.eat(chicken))
print(bear.eat(cow))
print(bear.eat(sheep))
print(bear.eat(leaves))
print(chicken.eat(bug))
print(cow.eat(grass))
print(fox.eat(chicken))
print(fox.eat(sheep))
print(giraffe.eat(leaves))
print(lion.eat(antelope))
print(lion.eat(cow))
print(panda.eat(leaves))
print(sheep.eat(grass))
print(grass.eat(sheep))